// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package sample.use.proto;

public final class JavaGrpcServerBase {
  private JavaGrpcServerBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JavaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JavaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JavaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JavaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014server.proto\"\036\n\013JavaRequest\022\017\n\007request" +
      "\030\001 \001(\t\" \n\014JavaResponse\022\020\n\010response\030\001 \001(\t" +
      "2\331\001\n\016JavaGrpcServer\022(\n\tunaryCall\022\014.JavaR" +
      "equest\032\r.JavaResponse\0220\n\017clientStreaming" +
      "\022\014.JavaRequest\032\r.JavaResponse(\001\0220\n\017serve" +
      "rStreaming\022\014.JavaRequest\032\r.JavaResponse0" +
      "\001\0229\n\026biDirectionalStreaming\022\014.JavaReques" +
      "t\032\r.JavaResponse(\0010\001B(\n\020sample.use.proto" +
      "B\022JavaGrpcServerBaseP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JavaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JavaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JavaRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_JavaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JavaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JavaResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
