// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package sample.use.proto;

public interface JavaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JavaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
