// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto

package sample.use.proto;

public interface JavaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JavaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
